name: Unity Build and Test

on: [push]
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Unity project
        uses: game-ci/unity-builder@v2.0.0
        with:
          unityVersion: 2021.3.19f1
          targetPlatform: StandaloneLinux64
      - name: Build C# code
        run: dotnet build --configuration Release --verbosity diagnostic ./Assets/Scripts || true
