name: Tests

on: workflow_dispatch

jobs:
  BashTest:
    runs-on: ubuntu-latest
    steps:
      - name: checkoutcode
        uses: actions/checkout@v2

      - name: Step 1
        id: step1
        run: |
          echo "Hello, world!"
          echo "{MY_VARIABLE}={123}" >> $GITHUB_STATE

      - name: Step 2
        run: |
          echo "The value of MY_VARIABLE is ${{state.MY_VARIABLE}}"
