name: Tests

on: workflow_dispatch
env:
  testArray: ()

jobs:
  BashTest:
    runs-on: ubuntu-latest
    steps:
      - name: checkoutcode
        uses: actions/checkout@v2

      - name: Step 1
        id: step1
        run: |
          myArray=("jeden" "dwa")
          myArray+=("trzy" "cztery")
          echo "::group::tytul"
          echo "::warning file=plik.txt::wiadomosc"
          echo "::endgroup::"
