name: Tests

on: workflow_dispatch

jobs:
  BashTest:
    runs-on: ubuntu-latest
    steps:
      - name: checkoutcode
        uses: actions/checkout@v2

      - name: Step 1
        id: step1
        run: |
          myArray=("jeden" "dwa")
          myArray+=("trzy" "cztery")
          echo "Hello, world!"
          for str in ${myArray[@]};do
            echo "savedArray+=$str" >> $GITHUB_ENV
          done
          

      - name: Step 2
        run: |
          myArray=${{env.savedArray}}
          for str in ${myArray[@]};do
            echo $str
          done
