name: Tests

on: workflow_dispatch
env:
  testArray: ()

jobs:
  BashTest:
    runs-on: ubuntu-latest
    steps:
      - name: checkoutcode
        uses: actions/checkout@v2

#       - name: Step 1
#         id: step1
#         run: |
#           myArray=("jeden" "dwa")
#           myArray+=("trzy" "cztery")
#           echo "::group::tytul"
#           echo "::warning file=plik.txt::wiadomosc"
#           echo "::group::grd"
#           echo "drugagrupa"
#           echo "::endgroup::"
#           echo "::endgroup::"
#       - name: Step 1
#         run: |
#           echo "MY_VAR=hello world" >> $GITHUB_ENV
#       - name: step 2
#         run: |
#           echo ${{env.MY_VAR}}
      - run: |
          echo "::group::abc"
          echo "a"
      - name: step 2
        run : |
          echo "b"
          echo "c"
          echo "::endgroup::"
